
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package exemplo;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 27;
  public static final int SEMICOLON = 14;
  public static final int ELSE = 10;
  public static final int NOTEQ = 21;
  public static final int RBRACE = 32;
  public static final int OR = 28;
  public static final int INT = 5;
  public static final int RPAREM = 30;
  public static final int MOREEQ = 24;
  public static final int CHAR = 4;
  public static final int SUM = 15;
  public static final int NOT = 26;
  public static final int RETURN = 12;
  public static final int MORET = 22;
  public static final int IF = 9;
  public static final int LBRACE = 31;
  public static final int LPAREM = 29;
  public static final int SUB = 16;
  public static final int ID_ = 2;
  public static final int COMMA = 13;
  public static final int LESST = 23;
  public static final int MULT = 17;
  public static final int EOF = 0;
  public static final int DEF = 11;
  public static final int DIV = 18;
  public static final int CONST = 8;
  public static final int error = 1;
  public static final int LESSEQ = 25;
  public static final int EQ = 20;
  public static final int ATT = 19;
  public static final int STR = 6;
  public static final int BOOL = 7;
  public static final int WS = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID_",
  "WS",
  "CHAR",
  "INT",
  "STR",
  "BOOL",
  "CONST",
  "IF",
  "ELSE",
  "DEF",
  "RETURN",
  "COMMA",
  "SEMICOLON",
  "SUM",
  "SUB",
  "MULT",
  "DIV",
  "ATT",
  "EQ",
  "NOTEQ",
  "MORET",
  "LESST",
  "MOREEQ",
  "LESSEQ",
  "NOT",
  "AND",
  "OR",
  "LPAREM",
  "RPAREM",
  "LBRACE",
  "RBRACE"
  };
}

